name: markdown2man
description: A GitHub Action to convert a markdown document into a man page.
branding:
  icon: book-open
  color: blue

inputs:
  markdown_file:
    description: Markdown file pathname to convert, relative to repository root.
    required: false
    default: README.md
  manpage_name:
    description: Man page name for converted document.
    required: true
  manpage_section:
    description: Section for converted man page.
    required: false
    default: "1"
  manpage_folder:
    description: Output folder for converted man page.
    required: false
    default: "."
  manpage_title:
    description: Title for converted manpage.
    required: false
    default: "Usage documentation"

runs:
  using: "docker"
  image: "Dockerfile"

  args:
#    - -v ./:/work/ /work/${{ inputs.markdown_file }} ${{ inputs.manpage_name }} -s ${{ inputs.manpage_section }} -t ${{ inputs.manpage_title }} -f /work/${{ inputs.manpage_folder }}
    - ${{ inputs.markdown_file }} ${{ inputs.manpage_name }} -s ${{ inputs.manpage_section }} -t ${{ inputs.manpage_title }} -f ${{ inputs.manpage_folder }}